dist:
  name: otelcol-azuregigwarm
  description: OpenTelemetry Collector with Azure GigWarm exporter
  output_path: ./bin
  otelcol_version: 0.137.0

exporters:
  # Azure GigWarm exporter
  - gomod: github.com/open-telemetry/otel-azuregigwarm-exporter/exporter/azuregigwarmexporter v0.1.0

  # Standard exporters
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.137.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.137.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.137.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.137.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.137.0
